export const NEW_PROYECT = 'NEW_PROYECT'
export const LIST_PROYECT = 'LIST_PROYECT'
export const ADD_PROYECT = 'ADD_PROYECT'
export const VALIDATE_NEW_PROYECT = 'VALIDATE_NEW_PROYECT'
export const ACTIVE_PROYECT = 'ACTIVE_PROYECT'
export const DELETE_PROYECT = 'DELETE_PROYECT'

export const LIST_TASK = 'LIST_TASK'
export const ADD_TASK = 'ADD_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const STATE_TASK = 'STATE_TASK'
export const ACTIVE_TASK = 'ACTIVE_TASK'
export const EDIT_TASK = 'EDIT_TASK'

export const ALERT_TRUE= 'ALERT_TRUE'
export const ALERT_FALSE = 'ALERT_FALSE'
